export { VeritecViewer } from "./veritec-viewer"
export type { IVeritecViewerRef, IVeritecViewerProps, IViewerDocument } from "./veritec-viewer.types"
export { createZoomPlugin } from "./plugins/zoom-plugin"
export type { IZoomPlugin } from "./plugins/zoom-plugin"
export { createPageTrackingPlugin } from "./plugins/page-tracking-plugin"
export type { IPageTrackingPlugin } from "./plugins/page-tracking-plugin"
export { useZoom, useCurrentPage } from "./hooks/use-viewer-selectors"
export { ViewerToolbar } from "./components/viewer-toolbar"
export { ThumbnailSidebar } from "./components/thumbnail-sidebar"
